#!/usr/bin/env bash
# Do something

index=1

while [ $index -lt 21 ]
do
  echo "$index"
  case $index in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( index++ ))
done
